# Generated by Django 2.0 on 2018-01-03 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='预订者')),
                ('start_time', models.DateTimeField(verbose_name='会议开始时间')),
                ('end_time', models.DateTimeField(verbose_name='会议开始时间')),
                ('duration', models.FloatField(verbose_name='会议持续时长')),
                ('subject', models.CharField(max_length=120, verbose_name='会议主题')),
                ('abstract', models.TextField(verbose_name='会议大纲')),
            ],
            options={
                'verbose_name': '会议室预定信息',
                'verbose_name_plural': '会议室预定信息',
            },
        ),
        migrations.CreateModel(
            name='MeetingInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name='邀约人')),
                ('member', models.TextField(verbose_name='会议成员')),
            ],
            options={
                'verbose_name': '会议邀约信息',
                'verbose_name_plural': '会议邀约信息',
            },
        ),
        migrations.CreateModel(
            name='MeetingRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会议室名称')),
                ('capacity', models.CharField(max_length=40, verbose_name='会议室容量')),
                ('screen', models.BooleanField(default=True, verbose_name='是否有电视/投影')),
                ('comment', models.CharField(max_length=150, verbose_name='其他说明')),
            ],
            options={
                'verbose_name': '会议室信息',
                'verbose_name_plural': '会议室信息',
            },
        ),
    ]
