# Generated by Django 2.0 on 2018-01-03 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmeeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='meeting_room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookmeeting.MeetingRoom', verbose_name='会议室'),
            preserve_default=False,
        ),
    ]
