# Generated by Django 2.0 on 2018-01-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmeeting', '0003_auto_20180105_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='picture',
            field=models.ImageField(default='meetingroom/default.png', upload_to='meetingroom/', verbose_name='会议室图片'),
        ),
    ]
