# Generated by Django 2.0 on 2018-01-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmeeting', '0004_meetingroom_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='book_time',
            field=models.DateTimeField(auto_now=True, verbose_name='发起预定时间'),
        ),
        migrations.AlterField(
            model_name='bookinginfo',
            name='duration',
            field=models.FloatField(verbose_name='会议持续时长（分钟）'),
        ),
    ]
