# Generated by Django 2.0 on 2018-01-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmeeting', '0005_auto_20180109_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetinginvitation',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bookmeeting.BookingInfo', verbose_name='会议'),
            preserve_default=False,
        ),
    ]
