# Generated by Django 2.0 on 2018-01-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmeeting', '0006_meetinginvitation_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetinginvitation',
            name='meeting',
        ),
        migrations.AddField(
            model_name='bookinginfo',
            name='member',
            field=models.TextField(blank=True, null=True, verbose_name='会议成员'),
        ),
        migrations.DeleteModel(
            name='MeetingInvitation',
        ),
    ]
