# Generated by Django 2.0 on 2018-01-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmeeting', '0007_auto_20180110_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='invitation',
            field=models.BooleanField(default=True, verbose_name='是否发送会议邀请'),
        ),
    ]
