# Generated by Django 2.0 on 2018-01-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmeeting', '0008_bookinginfo_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinginfo',
            name='member',
            field=models.TextField(verbose_name='会议成员'),
        ),
    ]
